# API Keys for Sentiment Analysis App
# Get these from the respective developer portals

# Twitter API v2: https://developer.twitter.com/
TWITTER_BEARER_TOKEN = "AAAAAAAAAAAAAAAAAAAAAI%2Bk3wEAAAAAXEWpXLgR3anRTJI7UdBc5XOBAoQ%3D4N0TnbcJXK5iaFjVggRqXx4Ao7mIuTGQMHdDVWLap0BJrChvjp"

# Reddit API: https://www.reddit.com/prefs/apps
REDDIT_CLIENT_ID = "KELVIN GITHUA"
REDDIT_CLIENT_SECRET = "9OimfoofFq3Hx5ebFyVDHbdXdCI7dg"

# NewsAPI: https://newsapi.org/
NEWSAPI_KEY = "08468b1346e74ce8809b16c2797ef8ed"